import Landing from './Landing'
import About from './About'
import Partner from './Partner'
import Error from './Error'
import Login from './Login'
import Register from './Register'
import Visas from './Visas'
import Tags from './Tags'
import SingleProduct from './SingleProduct'
export { Landing, About, Partner,  Error, Login, Register, Visas, Tags, SingleProduct }
