
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        SERVICE_ADD : "SERVICE_ADD",
        SERVICE_EDIT : "SERVICE_EDIT",
        CONFIGURATION_ADD : "CONFIGURATION_ADD",
        CONFIGURATION_EDIT : "CONFIGURATION_EDIT",
        USER_ADD : "USER_ADD",
        USER_EDIT : "USER_EDIT",
        ADMIN_ADD: "ADMIN_ADD",
        PARTNER_ADD : "PARTNER_ADD",
        PARTNER_EDIT : "PARTNER_EDIT",
        DOCUMENT_ADD : "DOCUMENT_ADD",
        DOCUMENT_EDIT : "DOCUMENT_EDIT",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        SERVICE_DELETE : "SERVICE_DELETE",
        USER_DELETE : "USER_DELETE",
        PARTNER_DELETE: "PARTNER_DELETE",
        DOCUMENT_DELETE: "DOCUMENT_DELETE",
    },
});
